### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by zhangchunsheng** [aliyun/alibabacloud-console-os#40]
> @alicloud/demo-console-os-vue-app@0.3.14 serve alibabacloud-console-os/example/SubApp/Vue
> vue-cli-service serve

 INFO  Starting development server...
95% emitting WebpackAssetsManifest(node:2655) UnhandledPromiseRejectionWarning: TypeError: Cannot convert object to primitive value
    at alibabacloud-console-os/example/SubApp/Vue/node_modules/_@alicloud_console-toolkit-plugin-os@0.3.14@@alicloud/console-toolkit-plugin-os/lib/index.js:71:56
    at Array.forEach (<anonymous>)
    at transform (alibabacloud-console-os/example/SubApp/Vue/node_modules/_@alicloud_console-toolkit-plugin-os@0.3.14@@alicloud/console-toolkit-plugin-os/lib/index.js:69:56)
    at SyncWaterfallHook.eval [as call] (eval at create (alibabacloud-console-os/example/SubApp/Vue/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:16)
    at SyncWaterfallHook.lazyCompileHook (alibabacloud-console-os/example/SubApp/Vue/node_modules/_tapable@1.1.3@tapable/lib/Hook.js:154:20)
    at WebpackAssetsManifest.toJSON (alibabacloud-console-os/example/SubApp/Vue/node_modules/_webpack-assets-manifest@3.1.1@webpack-assets-manifest/src/WebpackAssetsManifest.js:375:33)
    at JSON.stringify (<anonymous>)
    at WebpackAssetsManifest.toString (alibabacloud-console-os/example/SubApp/Vue/node_modules/_webpack-assets-manifest@3.1.1@webpack-assets-manifest/src/WebpackAssetsManifest.js:385:17)
    at WebpackAssetsManifest.handleEmit (alibabacloud-console-os/example/SubApp/Vue/node_modules/_webpack-assets-manifest@3.1.1@webpack-assets-manifest/src/WebpackAssetsManifest.js:484:55)
    at _next1 (eval at create (alibabacloud-console-os/example/SubApp/Vue/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (alibabacloud-console-os/example/SubApp/Vue/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:44:1)
    at alibabacloud-console-os/example/SubApp/Vue/node_modules/_copy-webpack-plugin@5.1.1@copy-webpack-plugin/dist/index.js:91:9
(node:2655) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2655) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

node --version
v12.7.0

npm --version
6.10.0

**Comment by Boelroy** [comment]
已经修复了 请用 @alicloud_console-toolkit-plugin-os@0.3.15
